POST http://localhost:8080/worker/create
Content-Type: application/json

  {
    "passportId": "Ac21212",
    "name": "ALi",
    "surname": "asdads",
    "workType": "FRONTEND",
    "salary": 11.2
  }